// Default California CIMIS locations — full active list from CIMIS API
// Source: https://et.water.ca.gov/api/station (145 active stations)
export interface DefaultLocation {
  id: string;
  name: string;
  weatherstation?: string;
  weatherstationID?: string;
  cimisStationId?: string;
  region?: string;
  state?: string;
  latitude: number;
  longitude: number;
}

export const DEFAULT_CALIFORNIA_LOCATIONS: DefaultLocation[] = [
  // ── Northern California ─────────────────────────────────────
  {
    id: 'cimis-43',
    name: 'McArthur',
    weatherstation: 'McArthur',
    weatherstationID: '43',
    cimisStationId: '43',
    region: 'Northern California',
    state: 'California',
    latitude: 41.063767,
    longitude: -121.45602
  },
  {
    id: 'cimis-90',
    name: 'Alturas',
    weatherstation: 'Alturas',
    weatherstationID: '90',
    cimisStationId: '90',
    region: 'Northern California',
    state: 'California',
    latitude: 41.438214,
    longitude: -120.48031
  },
  {
    id: 'cimis-91',
    name: 'Tulelake FS',
    weatherstation: 'Tulelake FS',
    weatherstationID: '91',
    cimisStationId: '91',
    region: 'Northern California',
    state: 'California',
    latitude: 41.958869,
    longitude: -121.47237
  },
  {
    id: 'cimis-222',
    name: 'Gerber South',
    weatherstation: 'Gerber South',
    weatherstationID: '222',
    cimisStationId: '222',
    region: 'Northern California',
    state: 'California',
    latitude: 40.040006,
    longitude: -122.154539
  },
  {
    id: 'cimis-224',
    name: 'Shasta College',
    weatherstation: 'Shasta College',
    weatherstationID: '224',
    cimisStationId: '224',
    region: 'Northern California',
    state: 'California',
    latitude: 40.63,
    longitude: -122.31
  },
  {
    id: 'cimis-225',
    name: 'Scott Valley',
    weatherstation: 'Scott Valley',
    weatherstationID: '225',
    cimisStationId: '225',
    region: 'Northern California',
    state: 'California',
    latitude: 41.577778,
    longitude: -122.838125
  },
  {
    id: 'cimis-236',
    name: 'Macdoel II',
    weatherstation: 'Macdoel II',
    weatherstationID: '236',
    cimisStationId: '236',
    region: 'Northern California',
    state: 'California',
    latitude: 41.802476,
    longitude: -121.996159
  },
  {
    id: 'cimis-244',
    name: 'Biggs',
    weatherstation: 'Biggs',
    weatherstationID: '244',
    cimisStationId: '244',
    region: 'Northern California',
    state: 'California',
    latitude: 39.386632,
    longitude: -121.835278
  },
  {
    id: 'cimis-250',
    name: 'Williams',
    weatherstation: 'Williams',
    weatherstationID: '250',
    cimisStationId: '250',
    region: 'Northern California',
    state: 'California',
    latitude: 39.210667,
    longitude: -122.168889
  },
  {
    id: 'cimis-259',
    name: 'Ferndale Plain',
    weatherstation: 'Ferndale Plain',
    weatherstationID: '259',
    cimisStationId: '259',
    region: 'Northern California',
    state: 'California',
    latitude: 40.604467,
    longitude: -124.243186
  },
  {
    id: 'cimis-260',
    name: 'Montague',
    weatherstation: 'Montague',
    weatherstationID: '260',
    cimisStationId: '260',
    region: 'Northern California',
    state: 'California',
    latitude: 41.798331,
    longitude: -122.463425
  },
  {
    id: 'cimis-261',
    name: 'Gazelle',
    weatherstation: 'Gazelle',
    weatherstationID: '261',
    cimisStationId: '261',
    region: 'Northern California',
    state: 'California',
    latitude: 41.533989,
    longitude: -122.532279
  },
  {
    id: 'cimis-263',
    name: 'Smith River',
    weatherstation: 'Smith River',
    weatherstationID: '263',
    cimisStationId: '263',
    region: 'Northern California',
    state: 'California',
    latitude: 41.894592,
    longitude: -124.165043
  },
  {
    id: 'cimis-264',
    name: 'Sierra Valley Center',
    weatherstation: 'Sierra Valley Center',
    weatherstationID: '264',
    cimisStationId: '264',
    region: 'Northern California',
    state: 'California',
    latitude: 39.777452,
    longitude: -120.273609
  },
  {
    id: 'cimis-267',
    name: 'Johnstonville',
    weatherstation: 'Johnstonville',
    weatherstationID: '267',
    cimisStationId: '267',
    region: 'Northern California',
    state: 'California',
    latitude: 40.364578,
    longitude: -120.559397
  },
  {
    id: 'cimis-268',
    name: 'Nubieber',
    weatherstation: 'Nubieber',
    weatherstationID: '268',
    cimisStationId: '268',
    region: 'Northern California',
    state: 'California',
    latitude: 41.105901,
    longitude: -121.165701
  },
  {
    id: 'cimis-272',
    name: 'Anderson',
    weatherstation: 'Anderson',
    weatherstationID: '272',
    cimisStationId: '272',
    region: 'Northern California',
    state: 'California',
    latitude: 40.434911,
    longitude: -122.247425
  },
  // ── Central California (North) ──────────────────────────────
  {
    id: 'cimis-6',
    name: 'Davis',
    weatherstation: 'Davis',
    weatherstationID: '6',
    cimisStationId: '6',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.535694,
    longitude: -121.77636
  },
  {
    id: 'cimis-13',
    name: 'Camino',
    weatherstation: 'Camino',
    weatherstationID: '13',
    cimisStationId: '13',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.753136,
    longitude: -120.7336
  },
  {
    id: 'cimis-47',
    name: 'Brentwood',
    weatherstation: 'Brentwood',
    weatherstationID: '47',
    cimisStationId: '47',
    region: 'Central California (North)',
    state: 'California',
    latitude: 37.928258,
    longitude: -121.6599
  },
  {
    id: 'cimis-70',
    name: 'Manteca',
    weatherstation: 'Manteca',
    weatherstationID: '70',
    cimisStationId: '70',
    region: 'Central California (North)',
    state: 'California',
    latitude: 37.834822,
    longitude: -121.22319
  },
  {
    id: 'cimis-77',
    name: 'Oakville',
    weatherstation: 'Oakville',
    weatherstationID: '77',
    cimisStationId: '77',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.428475,
    longitude: -122.41021
  },
  {
    id: 'cimis-83',
    name: 'Santa Rosa',
    weatherstation: 'Santa Rosa',
    weatherstationID: '83',
    cimisStationId: '83',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.40355,
    longitude: -122.79993
  },
  {
    id: 'cimis-84',
    name: 'Browns Valley',
    weatherstation: 'Browns Valley',
    weatherstationID: '84',
    cimisStationId: '84',
    region: 'Central California (North)',
    state: 'California',
    latitude: 39.252561,
    longitude: -121.31567
  },
  {
    id: 'cimis-103',
    name: 'Windsor',
    weatherstation: 'Windsor',
    weatherstationID: '103',
    cimisStationId: '103',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.52665,
    longitude: -122.813758
  },
  {
    id: 'cimis-106',
    name: 'Sanel Valley',
    weatherstation: 'Sanel Valley',
    weatherstationID: '106',
    cimisStationId: '106',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.982581,
    longitude: -123.08928
  },
  {
    id: 'cimis-131',
    name: 'Fair Oaks',
    weatherstation: 'Fair Oaks',
    weatherstationID: '131',
    cimisStationId: '131',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.649964,
    longitude: -121.21887
  },
  {
    id: 'cimis-139',
    name: 'Winters',
    weatherstation: 'Winters',
    weatherstationID: '139',
    cimisStationId: '139',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.501258,
    longitude: -121.97853
  },
  {
    id: 'cimis-140',
    name: 'Twitchell Island',
    weatherstation: 'Twitchell Island',
    weatherstationID: '140',
    cimisStationId: '140',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.121739,
    longitude: -121.674455
  },
  {
    id: 'cimis-144',
    name: 'Petaluma East',
    weatherstation: 'Petaluma East',
    weatherstationID: '144',
    cimisStationId: '144',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.266428,
    longitude: -122.61646
  },
  {
    id: 'cimis-157',
    name: 'Point San Pedro',
    weatherstation: 'Point San Pedro',
    weatherstationID: '157',
    cimisStationId: '157',
    region: 'Central California (North)',
    state: 'California',
    latitude: 37.995478,
    longitude: -122.467656
  },
  {
    id: 'cimis-158',
    name: 'Bennett Valley',
    weatherstation: 'Bennett Valley',
    weatherstationID: '158',
    cimisStationId: '158',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.419439,
    longitude: -122.65872
  },
  {
    id: 'cimis-170',
    name: 'Concord',
    weatherstation: 'Concord',
    weatherstationID: '170',
    cimisStationId: '170',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.015372,
    longitude: -122.02028
  },
  {
    id: 'cimis-171',
    name: 'Union City',
    weatherstation: 'Union City',
    weatherstationID: '171',
    cimisStationId: '171',
    region: 'Central California (North)',
    state: 'California',
    latitude: 37.598758,
    longitude: -122.05323
  },
  {
    id: 'cimis-178',
    name: 'Moraga',
    weatherstation: 'Moraga',
    weatherstationID: '178',
    cimisStationId: '178',
    region: 'Central California (North)',
    state: 'California',
    latitude: 37.837614,
    longitude: -122.14074
  },
  {
    id: 'cimis-187',
    name: 'Black Point',
    weatherstation: 'Black Point',
    weatherstationID: '187',
    cimisStationId: '187',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.090933,
    longitude: -122.5267
  },
  {
    id: 'cimis-191',
    name: 'Pleasanton',
    weatherstation: 'Pleasanton',
    weatherstationID: '191',
    cimisStationId: '191',
    region: 'Central California (North)',
    state: 'California',
    latitude: 37.663969,
    longitude: -121.88503
  },
  {
    id: 'cimis-195',
    name: 'Auburn',
    weatherstation: 'Auburn',
    weatherstationID: '195',
    cimisStationId: '195',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.887603,
    longitude: -121.10291
  },
  {
    id: 'cimis-211',
    name: 'Gilroy',
    weatherstation: 'Gilroy',
    weatherstationID: '211',
    cimisStationId: '211',
    region: 'Central California (North)',
    state: 'California',
    latitude: 37.015026,
    longitude: -121.53704
  },
  {
    id: 'cimis-212',
    name: 'Hastings Tract East',
    weatherstation: 'Hastings Tract East',
    weatherstationID: '212',
    cimisStationId: '212',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.278056,
    longitude: -121.74111
  },
  {
    id: 'cimis-213',
    name: 'El Cerrito',
    weatherstation: 'El Cerrito',
    weatherstationID: '213',
    cimisStationId: '213',
    region: 'Central California (North)',
    state: 'California',
    latitude: 37.931539,
    longitude: -122.302714
  },
  {
    id: 'cimis-226',
    name: 'Woodland',
    weatherstation: 'Woodland',
    weatherstationID: '226',
    cimisStationId: '226',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.672722,
    longitude: -121.81172
  },
  {
    id: 'cimis-227',
    name: 'Plymouth',
    weatherstation: 'Plymouth',
    weatherstationID: '227',
    cimisStationId: '227',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.508333,
    longitude: -120.79972
  },
  {
    id: 'cimis-228',
    name: 'Diamond Springs',
    weatherstation: 'Diamond Springs',
    weatherstationID: '228',
    cimisStationId: '228',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.636111,
    longitude: -120.79305
  },
  {
    id: 'cimis-235',
    name: 'Verona',
    weatherstation: 'Verona',
    weatherstationID: '235',
    cimisStationId: '235',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.797944,
    longitude: -121.61136
  },
  {
    id: 'cimis-242',
    name: 'Staten Island',
    weatherstation: 'Staten Island',
    weatherstationID: '242',
    cimisStationId: '242',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.192397,
    longitude: -121.510261
  },
  {
    id: 'cimis-243',
    name: 'Ryde',
    weatherstation: 'Ryde',
    weatherstationID: '243',
    cimisStationId: '243',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.249622,
    longitude: -121.555528
  },
  {
    id: 'cimis-246',
    name: 'Markleeville',
    weatherstation: 'Markleeville',
    weatherstationID: '246',
    cimisStationId: '246',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.773409,
    longitude: -119.79193
  },
  {
    id: 'cimis-247',
    name: 'Jersey Island',
    weatherstation: 'Jersey Island',
    weatherstationID: '247',
    cimisStationId: '247',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.033386,
    longitude: -121.701247
  },
  {
    id: 'cimis-248',
    name: 'Holt',
    weatherstation: 'Holt',
    weatherstationID: '248',
    cimisStationId: '248',
    region: 'Central California (North)',
    state: 'California',
    latitude: 37.932072,
    longitude: -121.396661
  },
  {
    id: 'cimis-249',
    name: 'Ripon',
    weatherstation: 'Ripon',
    weatherstationID: '249',
    cimisStationId: '249',
    region: 'Central California (North)',
    state: 'California',
    latitude: 37.755597,
    longitude: -121.266153
  },
  {
    id: 'cimis-253',
    name: 'Pescadero',
    weatherstation: 'Pescadero',
    weatherstationID: '253',
    cimisStationId: '253',
    region: 'Central California (North)',
    state: 'California',
    latitude: 37.255333,
    longitude: -122.3708
  },
  {
    id: 'cimis-254',
    name: 'Oakland Metro',
    weatherstation: 'Oakland Metro',
    weatherstationID: '254',
    cimisStationId: '254',
    region: 'Central California (North)',
    state: 'California',
    latitude: 37.718167,
    longitude: -122.197111
  },
  {
    id: 'cimis-262',
    name: 'Linden',
    weatherstation: 'Linden',
    weatherstationID: '262',
    cimisStationId: '262',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.065692,
    longitude: -121.071747
  },
  {
    id: 'cimis-273',
    name: 'WildHawk',
    weatherstation: 'WildHawk',
    weatherstationID: '273',
    cimisStationId: '273',
    region: 'Central California (North)',
    state: 'California',
    latitude: 38.479722,
    longitude: -121.314722
  },
  // ── Central California (South) ──────────────────────────────
  {
    id: 'cimis-2',
    name: 'FivePoints',
    weatherstation: 'FivePoints',
    weatherstationID: '2',
    cimisStationId: '2',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.336222,
    longitude: -120.11291
  },
  {
    id: 'cimis-5',
    name: 'Shafter',
    weatherstation: 'Shafter',
    weatherstationID: '5',
    cimisStationId: '5',
    region: 'Central California (South)',
    state: 'California',
    latitude: 35.532556,
    longitude: -119.28179
  },
  {
    id: 'cimis-7',
    name: 'Firebaugh/Telles',
    weatherstation: 'Firebaugh/Telles',
    weatherstationID: '7',
    cimisStationId: '7',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.851222,
    longitude: -120.59092
  },
  {
    id: 'cimis-15',
    name: 'Stratford',
    weatherstation: 'Stratford',
    weatherstationID: '15',
    cimisStationId: '15',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.157972,
    longitude: -119.85143
  },
  {
    id: 'cimis-39',
    name: 'Parlier',
    weatherstation: 'Parlier',
    weatherstationID: '39',
    cimisStationId: '39',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.597444,
    longitude: -119.50404
  },
  {
    id: 'cimis-71',
    name: 'Modesto',
    weatherstation: 'Modesto',
    weatherstationID: '71',
    cimisStationId: '71',
    region: 'Central California (South)',
    state: 'California',
    latitude: 37.645222,
    longitude: -121.18776
  },
  {
    id: 'cimis-80',
    name: 'Fresno State',
    weatherstation: 'Fresno State',
    weatherstationID: '80',
    cimisStationId: '80',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.820833,
    longitude: -119.74231
  },
  {
    id: 'cimis-104',
    name: 'De Laveaga',
    weatherstation: 'De Laveaga',
    weatherstationID: '104',
    cimisStationId: '104',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.997444,
    longitude: -121.99676
  },
  {
    id: 'cimis-105',
    name: 'Westlands',
    weatherstation: 'Westlands',
    weatherstationID: '105',
    cimisStationId: '105',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.634028,
    longitude: -120.38181
  },
  {
    id: 'cimis-113',
    name: 'King City-Oasis Rd.',
    weatherstation: 'King City-Oasis Rd.',
    weatherstationID: '113',
    cimisStationId: '113',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.121083,
    longitude: -121.08457
  },
  {
    id: 'cimis-114',
    name: 'Arroyo Seco',
    weatherstation: 'Arroyo Seco',
    weatherstationID: '114',
    cimisStationId: '114',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.347306,
    longitude: -121.29135
  },
  {
    id: 'cimis-116',
    name: 'Salinas North',
    weatherstation: 'Salinas North',
    weatherstationID: '116',
    cimisStationId: '116',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.716806,
    longitude: -121.69189
  },
  {
    id: 'cimis-124',
    name: 'Panoche',
    weatherstation: 'Panoche',
    weatherstationID: '124',
    cimisStationId: '124',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.890056,
    longitude: -120.73141
  },
  {
    id: 'cimis-125',
    name: 'Arvin-Edison',
    weatherstation: 'Arvin-Edison',
    weatherstationID: '125',
    cimisStationId: '125',
    region: 'Central California (South)',
    state: 'California',
    latitude: 35.205583,
    longitude: -118.77841
  },
  {
    id: 'cimis-126',
    name: 'San Benito',
    weatherstation: 'San Benito',
    weatherstationID: '126',
    cimisStationId: '126',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.854833,
    longitude: -121.36275
  },
  {
    id: 'cimis-129',
    name: 'Pajaro',
    weatherstation: 'Pajaro',
    weatherstationID: '129',
    cimisStationId: '129',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.902778,
    longitude: -121.74193
  },
  {
    id: 'cimis-143',
    name: 'San Juan Valley',
    weatherstation: 'San Juan Valley',
    weatherstationID: '143',
    cimisStationId: '143',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.822861,
    longitude: -121.46787
  },
  {
    id: 'cimis-146',
    name: 'Belridge',
    weatherstation: 'Belridge',
    weatherstationID: '146',
    cimisStationId: '146',
    region: 'Central California (South)',
    state: 'California',
    latitude: 35.505833,
    longitude: -119.69114
  },
  {
    id: 'cimis-182',
    name: 'Delano',
    weatherstation: 'Delano',
    weatherstationID: '182',
    cimisStationId: '182',
    region: 'Central California (South)',
    state: 'California',
    latitude: 35.833,
    longitude: -119.25596
  },
  {
    id: 'cimis-193',
    name: 'Pacific Grove',
    weatherstation: 'Pacific Grove',
    weatherstationID: '193',
    cimisStationId: '193',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.633222,
    longitude: -121.93486
  },
  {
    id: 'cimis-194',
    name: 'Oakdale',
    weatherstation: 'Oakdale',
    weatherstationID: '194',
    cimisStationId: '194',
    region: 'Central California (South)',
    state: 'California',
    latitude: 37.727194,
    longitude: -120.85086
  },
  {
    id: 'cimis-205',
    name: 'Coalinga',
    weatherstation: 'Coalinga',
    weatherstationID: '205',
    cimisStationId: '205',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.175833,
    longitude: -120.36027
  },
  {
    id: 'cimis-206',
    name: 'Denair II',
    weatherstation: 'Denair II',
    weatherstationID: '206',
    cimisStationId: '206',
    region: 'Central California (South)',
    state: 'California',
    latitude: 37.545869,
    longitude: -120.75453
  },
  {
    id: 'cimis-209',
    name: 'Watsonville West II',
    weatherstation: 'Watsonville West II',
    weatherstationID: '209',
    cimisStationId: '209',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.913083,
    longitude: -121.82365
  },
  {
    id: 'cimis-210',
    name: 'Carmel',
    weatherstation: 'Carmel',
    weatherstationID: '210',
    cimisStationId: '210',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.540889,
    longitude: -121.88196
  },
  {
    id: 'cimis-214',
    name: 'Salinas South II',
    weatherstation: 'Salinas South II',
    weatherstationID: '214',
    cimisStationId: '214',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.625619,
    longitude: -121.537889
  },
  {
    id: 'cimis-229',
    name: 'Laguna Seca',
    weatherstation: 'Laguna Seca',
    weatherstationID: '229',
    cimisStationId: '229',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.570111,
    longitude: -121.7865
  },
  {
    id: 'cimis-252',
    name: 'Soledad II',
    weatherstation: 'Soledad II',
    weatherstationID: '252',
    cimisStationId: '252',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.456728,
    longitude: -121.344388
  },
  {
    id: 'cimis-258',
    name: 'Lemon Cove',
    weatherstation: 'Lemon Cove',
    weatherstationID: '258',
    cimisStationId: '258',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.376917,
    longitude: -119.037972
  },
  {
    id: 'cimis-269',
    name: 'Los Banos II',
    weatherstation: 'Los Banos II',
    weatherstationID: '269',
    cimisStationId: '269',
    region: 'Central California (South)',
    state: 'California',
    latitude: 37.108935,
    longitude: -120.797387
  },
  {
    id: 'cimis-270',
    name: 'COS Tulare',
    weatherstation: 'COS Tulare',
    weatherstationID: '270',
    cimisStationId: '270',
    region: 'Central California (South)',
    state: 'California',
    latitude: 36.189399,
    longitude: -119.285207
  },
  // ── Southern California ─────────────────────────────────────
  {
    id: 'cimis-35',
    name: 'Bishop',
    weatherstation: 'Bishop',
    weatherstationID: '35',
    cimisStationId: '35',
    region: 'Southern California',
    state: 'California',
    latitude: 37.358514,
    longitude: -118.40553
  },
  {
    id: 'cimis-41',
    name: 'Calipatria/Mulberry',
    weatherstation: 'Calipatria/Mulberry',
    weatherstationID: '41',
    cimisStationId: '41',
    region: 'Southern California',
    state: 'California',
    latitude: 33.042986,
    longitude: -115.41585
  },
  {
    id: 'cimis-44',
    name: 'U.C. Riverside',
    weatherstation: 'U.C. Riverside',
    weatherstationID: '44',
    cimisStationId: '44',
    region: 'Southern California',
    state: 'California',
    latitude: 33.964942,
    longitude: -117.33698
  },
  {
    id: 'cimis-52',
    name: 'San Luis Obispo',
    weatherstation: 'San Luis Obispo',
    weatherstationID: '52',
    cimisStationId: '52',
    region: 'Southern California',
    state: 'California',
    latitude: 35.305442,
    longitude: -120.66178
  },
  {
    id: 'cimis-64',
    name: 'Santa Ynez',
    weatherstation: 'Santa Ynez',
    weatherstationID: '64',
    cimisStationId: '64',
    region: 'Southern California',
    state: 'California',
    latitude: 34.583144,
    longitude: -120.07924
  },
  {
    id: 'cimis-75',
    name: 'Irvine',
    weatherstation: 'Irvine',
    weatherstationID: '75',
    cimisStationId: '75',
    region: 'Southern California',
    state: 'California',
    latitude: 33.68845,
    longitude: -117.72118
  },
  {
    id: 'cimis-78',
    name: 'Pomona',
    weatherstation: 'Pomona',
    weatherstationID: '78',
    cimisStationId: '78',
    region: 'Southern California',
    state: 'California',
    latitude: 34.056589,
    longitude: -117.81307
  },
  {
    id: 'cimis-87',
    name: 'Meloland',
    weatherstation: 'Meloland',
    weatherstationID: '87',
    cimisStationId: '87',
    region: 'Southern California',
    state: 'California',
    latitude: 32.806183,
    longitude: -115.44626
  },
  {
    id: 'cimis-88',
    name: 'Cuyama',
    weatherstation: 'Cuyama',
    weatherstationID: '88',
    cimisStationId: '88',
    region: 'Southern California',
    state: 'California',
    latitude: 34.942525,
    longitude: -119.6738
  },
  {
    id: 'cimis-99',
    name: 'Santa Monica',
    weatherstation: 'Santa Monica',
    weatherstationID: '99',
    cimisStationId: '99',
    region: 'Southern California',
    state: 'California',
    latitude: 34.044311,
    longitude: -118.47689
  },
  {
    id: 'cimis-107',
    name: 'Santa Barbara',
    weatherstation: 'Santa Barbara',
    weatherstationID: '107',
    cimisStationId: '107',
    region: 'Southern California',
    state: 'California',
    latitude: 34.437353,
    longitude: -119.73742
  },
  {
    id: 'cimis-117',
    name: 'Victorville',
    weatherstation: 'Victorville',
    weatherstationID: '117',
    cimisStationId: '117',
    region: 'Southern California',
    state: 'California',
    latitude: 34.475914,
    longitude: -117.26351
  },
  {
    id: 'cimis-135',
    name: 'Blythe NE',
    weatherstation: 'Blythe NE',
    weatherstationID: '135',
    cimisStationId: '135',
    region: 'Southern California',
    state: 'California',
    latitude: 33.662869,
    longitude: -114.55811
  },
  {
    id: 'cimis-136',
    name: 'Oasis',
    weatherstation: 'Oasis',
    weatherstationID: '136',
    cimisStationId: '136',
    region: 'Southern California',
    state: 'California',
    latitude: 33.523694,
    longitude: -116.15575
  },
  {
    id: 'cimis-147',
    name: 'Otay Lake',
    weatherstation: 'Otay Lake',
    weatherstationID: '147',
    cimisStationId: '147',
    region: 'Southern California',
    state: 'California',
    latitude: 32.628208,
    longitude: -116.93928
  },
  {
    id: 'cimis-150',
    name: 'Miramar',
    weatherstation: 'Miramar',
    weatherstationID: '150',
    cimisStationId: '150',
    region: 'Southern California',
    state: 'California',
    latitude: 32.885847,
    longitude: -117.14314
  },
  {
    id: 'cimis-151',
    name: 'Ripley',
    weatherstation: 'Ripley',
    weatherstationID: '151',
    cimisStationId: '151',
    region: 'Southern California',
    state: 'California',
    latitude: 33.532222,
    longitude: -114.63389
  },
  {
    id: 'cimis-152',
    name: 'Camarillo',
    weatherstation: 'Camarillo',
    weatherstationID: '152',
    cimisStationId: '152',
    region: 'Southern California',
    state: 'California',
    latitude: 34.219386,
    longitude: -118.99244
  },
  {
    id: 'cimis-153',
    name: 'Escondido SPV',
    weatherstation: 'Escondido SPV',
    weatherstationID: '153',
    cimisStationId: '153',
    region: 'Southern California',
    state: 'California',
    latitude: 33.08105,
    longitude: -116.9757
  },
  {
    id: 'cimis-159',
    name: 'Monrovia',
    weatherstation: 'Monrovia',
    weatherstationID: '159',
    cimisStationId: '159',
    region: 'Southern California',
    state: 'California',
    latitude: 34.146372,
    longitude: -117.9858
  },
  {
    id: 'cimis-160',
    name: 'San Luis Obispo West',
    weatherstation: 'San Luis Obispo West',
    weatherstationID: '160',
    cimisStationId: '160',
    region: 'Southern California',
    state: 'California',
    latitude: 35.335261,
    longitude: -120.73588
  },
  {
    id: 'cimis-163',
    name: 'Atascadero',
    weatherstation: 'Atascadero',
    weatherstationID: '163',
    cimisStationId: '163',
    region: 'Southern California',
    state: 'California',
    latitude: 35.472556,
    longitude: -120.64814
  },
  {
    id: 'cimis-165',
    name: 'Sisquoc',
    weatherstation: 'Sisquoc',
    weatherstationID: '165',
    cimisStationId: '165',
    region: 'Southern California',
    state: 'California',
    latitude: 34.841878,
    longitude: -120.21274
  },
  {
    id: 'cimis-173',
    name: 'Torrey Pines',
    weatherstation: 'Torrey Pines',
    weatherstationID: '173',
    cimisStationId: '173',
    region: 'Southern California',
    state: 'California',
    latitude: 32.901867,
    longitude: -117.25046
  },
  {
    id: 'cimis-174',
    name: 'Long Beach',
    weatherstation: 'Long Beach',
    weatherstationID: '174',
    cimisStationId: '174',
    region: 'Southern California',
    state: 'California',
    latitude: 33.798697,
    longitude: -118.09479
  },
  {
    id: 'cimis-179',
    name: 'Winchester',
    weatherstation: 'Winchester',
    weatherstationID: '179',
    cimisStationId: '179',
    region: 'Southern California',
    state: 'California',
    latitude: 33.663325,
    longitude: -117.09338
  },
  {
    id: 'cimis-181',
    name: 'Westmorland North',
    weatherstation: 'Westmorland North',
    weatherstationID: '181',
    cimisStationId: '181',
    region: 'Southern California',
    state: 'California',
    latitude: 33.078611,
    longitude: -115.66056
  },
  {
    id: 'cimis-183',
    name: 'Owens Lake North',
    weatherstation: 'Owens Lake North',
    weatherstationID: '183',
    cimisStationId: '183',
    region: 'Southern California',
    state: 'California',
    latitude: 36.488611,
    longitude: -117.91944
  },
  {
    id: 'cimis-184',
    name: 'San Diego II',
    weatherstation: 'San Diego II',
    weatherstationID: '184',
    cimisStationId: '184',
    region: 'Southern California',
    state: 'California',
    latitude: 32.729578,
    longitude: -117.13934
  },
  {
    id: 'cimis-189',
    name: 'Owens Lake South',
    weatherstation: 'Owens Lake South',
    weatherstationID: '189',
    cimisStationId: '189',
    region: 'Southern California',
    state: 'California',
    latitude: 36.358628,
    longitude: -117.94387
  },
  {
    id: 'cimis-192',
    name: 'Lake Arrowhead',
    weatherstation: 'Lake Arrowhead',
    weatherstationID: '192',
    cimisStationId: '192',
    region: 'Southern California',
    state: 'California',
    latitude: 34.255942,
    longitude: -117.21814
  },
  {
    id: 'cimis-197',
    name: 'Palmdale',
    weatherstation: 'Palmdale',
    weatherstationID: '197',
    cimisStationId: '197',
    region: 'Southern California',
    state: 'California',
    latitude: 34.614981,
    longitude: -118.03249
  },
  {
    id: 'cimis-199',
    name: 'Big Bear Lake',
    weatherstation: 'Big Bear Lake',
    weatherstationID: '199',
    cimisStationId: '199',
    region: 'Southern California',
    state: 'California',
    latitude: 34.237419,
    longitude: -116.86571
  },
  {
    id: 'cimis-200',
    name: 'Indio 2',
    weatherstation: 'Indio 2',
    weatherstationID: '200',
    cimisStationId: '200',
    region: 'Southern California',
    state: 'California',
    latitude: 33.748586,
    longitude: -116.2529
  },
  {
    id: 'cimis-202',
    name: 'Nipomo',
    weatherstation: 'Nipomo',
    weatherstationID: '202',
    cimisStationId: '202',
    region: 'Southern California',
    state: 'California',
    latitude: 35.028281,
    longitude: -120.56003
  },
  {
    id: 'cimis-204',
    name: 'Santa Clarita',
    weatherstation: 'Santa Clarita',
    weatherstationID: '204',
    cimisStationId: '204',
    region: 'Southern California',
    state: 'California',
    latitude: 34.426361,
    longitude: -118.51758
  },
  {
    id: 'cimis-207',
    name: 'Borrego Springs',
    weatherstation: 'Borrego Springs',
    weatherstationID: '207',
    cimisStationId: '207',
    region: 'Southern California',
    state: 'California',
    latitude: 33.268447,
    longitude: -116.36505
  },
  {
    id: 'cimis-208',
    name: 'La Quinta II',
    weatherstation: 'La Quinta II',
    weatherstationID: '208',
    cimisStationId: '208',
    region: 'Southern California',
    state: 'California',
    latitude: 33.678186,
    longitude: -116.27299
  },
  {
    id: 'cimis-215',
    name: 'Chatsworth',
    weatherstation: 'Chatsworth',
    weatherstationID: '215',
    cimisStationId: '215',
    region: 'Southern California',
    state: 'California',
    latitude: 34.291331,
    longitude: -118.57004
  },
  {
    id: 'cimis-216',
    name: 'Arleta',
    weatherstation: 'Arleta',
    weatherstationID: '216',
    cimisStationId: '216',
    region: 'Southern California',
    state: 'California',
    latitude: 34.256111,
    longitude: -118.38278
  },
  {
    id: 'cimis-217',
    name: 'Moorpark',
    weatherstation: 'Moorpark',
    weatherstationID: '217',
    cimisStationId: '217',
    region: 'Southern California',
    state: 'California',
    latitude: 34.269031,
    longitude: -118.849319
  },
  {
    id: 'cimis-218',
    name: 'Thermal South',
    weatherstation: 'Thermal South',
    weatherstationID: '218',
    cimisStationId: '218',
    region: 'Southern California',
    state: 'California',
    latitude: 33.595694,
    longitude: -116.15811
  },
  {
    id: 'cimis-220',
    name: 'Palmdale Central',
    weatherstation: 'Palmdale Central',
    weatherstationID: '220',
    cimisStationId: '220',
    region: 'Southern California',
    state: 'California',
    latitude: 34.592222,
    longitude: -118.1275
  },
  {
    id: 'cimis-221',
    name: 'Cadiz Valley',
    weatherstation: 'Cadiz Valley',
    weatherstationID: '221',
    cimisStationId: '221',
    region: 'Southern California',
    state: 'California',
    latitude: 34.513611,
    longitude: -115.51056
  },
  {
    id: 'cimis-223',
    name: 'North Hollywood',
    weatherstation: 'North Hollywood',
    weatherstationID: '223',
    cimisStationId: '223',
    region: 'Southern California',
    state: 'California',
    latitude: 34.142911,
    longitude: -118.36632
  },
  {
    id: 'cimis-231',
    name: 'Lompoc',
    weatherstation: 'Lompoc',
    weatherstationID: '231',
    cimisStationId: '231',
    region: 'Southern California',
    state: 'California',
    latitude: 34.672222,
    longitude: -120.51306
  },
  {
    id: 'cimis-232',
    name: 'Santa Maria II',
    weatherstation: 'Santa Maria II',
    weatherstationID: '232',
    cimisStationId: '232',
    region: 'Southern California',
    state: 'California',
    latitude: 34.913472,
    longitude: -120.46478
  },
  {
    id: 'cimis-233',
    name: 'Joshua Tree',
    weatherstation: 'Joshua Tree',
    weatherstationID: '233',
    cimisStationId: '233',
    region: 'Southern California',
    state: 'California',
    latitude: 34.138147,
    longitude: -116.21319
  },
  {
    id: 'cimis-237',
    name: 'Temecula East III',
    weatherstation: 'Temecula East III',
    weatherstationID: '237',
    cimisStationId: '237',
    region: 'Southern California',
    state: 'California',
    latitude: 33.55281,
    longitude: -117.043302
  },
  {
    id: 'cimis-239',
    name: 'Hemet',
    weatherstation: 'Hemet',
    weatherstationID: '239',
    cimisStationId: '239',
    region: 'Southern California',
    state: 'California',
    latitude: 33.664747,
    longitude: -116.955121
  },
  {
    id: 'cimis-240',
    name: 'Perris - Menifee',
    weatherstation: 'Perris - Menifee',
    weatherstationID: '240',
    cimisStationId: '240',
    region: 'Southern California',
    state: 'California',
    latitude: 33.76,
    longitude: -117.2
  },
  {
    id: 'cimis-241',
    name: 'San Clemente',
    weatherstation: 'San Clemente',
    weatherstationID: '241',
    cimisStationId: '241',
    region: 'Southern California',
    state: 'California',
    latitude: 33.4625,
    longitude: -117.586111
  },
  {
    id: 'cimis-245',
    name: 'Coto de Caza',
    weatherstation: 'Coto de Caza',
    weatherstationID: '245',
    cimisStationId: '245',
    region: 'Southern California',
    state: 'California',
    latitude: 33.621667,
    longitude: -117.585278
  },
  {
    id: 'cimis-251',
    name: 'Highland',
    weatherstation: 'Highland',
    weatherstationID: '251',
    cimisStationId: '251',
    region: 'Southern California',
    state: 'California',
    latitude: 34.112042,
    longitude: -117.1857
  },
  {
    id: 'cimis-256',
    name: 'Lancaster',
    weatherstation: 'Lancaster',
    weatherstationID: '256',
    cimisStationId: '256',
    region: 'Southern California',
    state: 'California',
    latitude: 34.759475,
    longitude: -117.991997
  },
  {
    id: 'cimis-257',
    name: 'Ridgecrest',
    weatherstation: 'Ridgecrest',
    weatherstationID: '257',
    cimisStationId: '257',
    region: 'Southern California',
    state: 'California',
    latitude: 35.659128,
    longitude: -117.636925
  },
  {
    id: 'cimis-265',
    name: 'Paso Robles',
    weatherstation: 'Paso Robles',
    weatherstationID: '265',
    cimisStationId: '265',
    region: 'Southern California',
    state: 'California',
    latitude: 35.692266,
    longitude: -120.64855
  },
  {
    id: 'cimis-266',
    name: 'Shandon',
    weatherstation: 'Shandon',
    weatherstationID: '266',
    cimisStationId: '266',
    region: 'Southern California',
    state: 'California',
    latitude: 35.643787,
    longitude: -120.403229
  },
  {
    id: 'cimis-271',
    name: 'Pauma Valley',
    weatherstation: 'Pauma Valley',
    weatherstationID: '271',
    cimisStationId: '271',
    region: 'Southern California',
    state: 'California',
    latitude: 33.299583,
    longitude: -116.979719
  },
];
