// EmailJS Configuration
// 
// To set up email notifications:
// 
// 1. Go to https://www.emailjs.com/ and create a free account
// 2. Create a new service (Gmail, Outlook, etc.)
// 3. Create a new template with these variables:
//    - to_email: {{to_email}}
//    - to_name: {{to_name}}
//    - subject: {{subject}}
//    - html_content: {{{html_content}}}
//    - location_count: {{location_count}}
//    - report_date: {{report_date}}
// 
// 4. Update the constants below with your EmailJS details:

export const EMAIL_CONFIG = {
  SERVICE_ID: 'service_weather_app', // Replace with your EmailJS service ID
  TEMPLATE_ID: 'template_weather_report', // Replace with your EmailJS template ID
  PUBLIC_KEY: 'your_public_key_here', // Replace with your EmailJS public key
};

// Example EmailJS Template HTML:
/* 
Subject: Weekly Weather Report - {{report_date}}

HTML Content:
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
  <h1>Weekly Weather Report</h1>
  <p>Hello {{to_name}},</p>
  <p>Here's your weekly weather report for {{location_count}} location(s):</p>
  
  {{{html_content}}}
  
  <hr>
  <p style="color: #666; font-size: 12px;">
    This report was generated by ET Weather App
  </p>
</div>
*/